movies/urls.py
from django.urls import path, include #Configurar urls para dirigir
from . import views #Importación de las vistas creadas

#urls a direccionar
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:movie_id>/", views.movie_detail, name="movie_detail"),
    path("your_name/", views.get_name, name="get_name"),
    path("<int:movie_id>/review/", views.get_review, name="get_review"),
    path("login/", views.user_login, name="login"),
    path("logout/", views.user_logout, name="logout"),
    path('register/', views.register_view, name='register'), # URL para el registro
    path('login/', views.get_return, name='get_return') #para regresar
]

mymovies/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
]

movies/models.py
#modelos definen las tablas de base de datos para una aplicación de gestión de películas en Django. 
from django.db import models #Importa los modelos de django 
from django.contrib.auth.models import User #Autentificar el usuario en Django
from django.core.validators import MaxValueValidator, MinValueValidator #Validar que los campos estan en el rango predefinido


#Modelo (Tabla) para genero de película y sus atributos
class Genre(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

#Modelo (Tabla) para actores y sus atributos
class Job(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

#Modelo (Tabla) para genero de película y sus atributos
class Person(models.Model):
    name = models.CharField(max_length=128)

    def __str__(self):
        return self.name

#Modelo (Tabla) para película y sus atributos
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import User

class Movie(models.Model):
    title = models.CharField(max_length=200)
    overview = models.TextField()
    release_date = models.DateTimeField()
    running_time = models.IntegerField()
    budget = models.IntegerField(blank=True)
    tmdb_id = models.IntegerField(blank=True, unique=True)
    revenue = models.IntegerField(blank=True)
    poster_path = models.URLField(blank=True)
    genres = models.ManyToManyField(Genre)
    credits = models.ManyToManyField(Person, through="MovieCredit")

    def average_rating(self):
        reviews = MovieReview.objects.filter(movie=self)
        if reviews:
            total_rating = sum(review.rating for review in reviews)
            return total_rating / len(reviews)
        else:
            return 0

    def __str__(self):
        return self.title + ' ' + str(self.release_date.year)


#Modelo (Tabla) para los creditos de la película y sus atributos
class MovieCredit(models.Model):
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    job = models.ForeignKey(Job, on_delete=models.CASCADE)

#Modelo (Tabla) para hcer la reseña de la película y sus atributos
class MovieReview(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    rating = models.PositiveSmallIntegerField(validators=[MinValueValidator(1),
                                                          MaxValueValidator(100)])
    review = models.TextField(blank=True)

movies/forms.py
#se utilizó para las pruebas de caja de texto en clase
from django import forms


class NameForm(forms.Form):
    your_name = forms.CharField(label="Nombre", max_length=100, help_text="100 characters max.", 
                                error_messages={"required": "El nombre es obligatorio"},
                                widget=forms.Textarea(attrs={"class":"text-gray-400", "rows": 3, "cols": 60}))

movies/views.py
from django.http import HttpResponse, HttpResponseRedirect #Devolver un http y redireccionar a otra url
from movies.models import Movie, MovieReview, MovieCredit #Importación de modelos (tablas)
from .forms import NameForm #Importación de formulario para el nombre (Pruebas)
from .formR import ReviewF #Importación de formulario para el review
from django.shortcuts import render, get_object_or_404, redirect #render=devolver html, get_object_or_404=obtener objeto de la BD y lanzar excepción, redirect=dirigir a una url especifica
from django.contrib.auth.models import User #Presenta al usuario
from django.urls import reverse #Obtener url de una vista dando su nombre y parámetros
from django.db.models import Avg #Calucular el promedio
from django.contrib.auth import authenticate, login, logout
from .formsU import LoginForm
from django.urls import reverse
from urllib.parse import urlencode
from django.db.models import Count
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm

####No se utiliza, se uso como prueba####
def get_name(request):
    # if this is a POST request we need to process the form data
    if request.method == "POST":
        # create a form instance and populate it with data from the request:
        form = NameForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            print(form.cleaned_data)
            return render(request, "movies/name_ok.html", {"form":form})
    # if a GET (or any other method) we'll create a blank form
    else:
        form = NameForm()
    return render(request, "movies/name.html", {"form": form})

def user_logout(request):
    logout(request)
    return redirect('index')
    
def get_review(request, movie_id):
    #Selectiva para verificar que el usuario inicio sesión sino te direcciona a hacerlo
    if request.user.is_authenticated:
        #Encontrar la película con el ID y si no esta lanzar excepción
        movie = get_object_or_404(Movie, pk=movie_id)
        #Selectiva para verificar que ya se envio el formulario
        if request.method == 'POST':
            #Crear instacia con los datos enviados en la soliciud POST
            form = ReviewF(request.POST)
            #Validar el formulario según las reglas en el formulario
            if form.is_valid():
                #Asiganción de lo valores enviados
                rating = form.cleaned_data['rating']
                review_text = form.cleaned_data['review']
                #Nueva instancia en el modelo, se alamcena en la base de datos del modelo review
                MovieReview.objects.create(user=request.user, movie=movie, rating=rating, review=review_text)
                
                #Redirecciona al html de movie_detail de la película de la cual hiciste la reseña
                return redirect('movie_detail', movie_id=movie_id)
        else:
            #Crear instancia del formulario (GET), inicializando el nombre de a película
            form = ReviewF(initial={'movie_name': movie.title})
        #Retorno del fromulario y plantilla del review para realizar la reseña
        return render(request, 'movies/review.html', {'form': form, 'movie_name': movie.title, 'movie_id': movie_id})
    else:
        #Direcciona a iniciar sesión
        login_url = reverse('login')
        query_string = urlencode({'next': reverse('movie_detail', args=[movie_id])})
        login_url_with_query = f"{login_url}?{query_string}"
        return redirect(login_url_with_query)

#Función para el depliegue del index (índice)
def index(request):
    # Asiganción del modelo y orden por fecha de lanzamiento en orden descendente
    movies = Movie.objects.all().order_by('-release_date')
    # Asignación de parámetros
    context = {
        'movie_list': movies
    }
    # Retorno de variables y solicitud de HTTP de la plantilla index.html
    return render(request, "movies/index.html", context=context)

#Función para mostrar los detalles de la película
def movie_detail(request, movie_id):
    #Asiganción de modelos a varaibles en relación al id de la movie
    movie = Movie.objects.get(pk=movie_id)
    reviews = MovieReview.objects.filter(movie=movie)
    actors = MovieCredit.objects.filter(movie=movie)
    genres = movie.genres.all()
    
    # Calcular el promedio de los valores de raiting
    average_rating = reviews.aggregate(Avg('rating'))['rating__avg']
    
    recommendations = Movie.objects.filter(genres__in=genres).exclude(id=movie_id).annotate(
        num_genres=Count('genres')
    ).filter(num_genres__gte=2).distinct()
    
    #Asignar todo lo que se envia como parámetro
    context = {
        'movie': movie,
        'review_list': reviews,
        'recommendations': recommendations,
        'actors': actors,
        'average_rating': average_rating 
    }
    #Retorno a de valores a la plantilla movie_detail.html
    return render(request, "movies/movie_detail.html", context=context)
    
def user_login(request):
    next_url = request.GET.get('next', reverse('index'))
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect(next_url)
            else:
                # Agregar un mensaje de error
                messages.error(request, "Invalid username or password.")
    else:
        form = LoginForm()
    return render(request, 'movies/login.html', {'form': form, 'login_page': True})
    
def register_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('index')
    else:
        form = UserCreationForm()
    return render(request, 'movies/register.html', {'form': form})

def get_return(request):
    return render(request, 'login.html')

movies/templates/movies/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Movies</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="/static/movies/css/output.css" rel="stylesheet">
    <script src="https://unpkg.com/htmx.org@1.9.12" integrity="sha384-ujb1lZYygJmzgSwoxRggbCHcjc0rB2XoQrxeTUQyRjrOnlCoYta87iKBWq3EsdM2" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/hyperscript.org@0.9.12"></script>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet">

</head>
<body class="bg-black font-poppins max-w-4xl mx-auto text-white">
    <header class="h-24 md:h-25 w-full mx-auto mt-5 border-b-2 border-blue-700 md:items-center md:justify-between">
        <h1 class="font-bold text-3xl text-center md:text-center mx-auto mb-4 md:mb-0">My Movies</h1>
        {% if not login_page %}
        <div class="text-center md:text-right md:mt-0">
            {% if user.is_authenticated %}
            <p class="inline-block md:mr-4 "><strong>Hi, {{ user.username }}</strong></p>
            <a href="{% url 'logout' %}" class="inline-block px-4 py-2 bg-red-600 text-white no-underline rounded cursor-pointer">Logout</a>
            {% else %}
            <a href="{% url 'login' %}" class="inline-block px-4 py-2 bg-blue-700 text-white no-underline rounded cursor-pointer">Login</a>
            {% endif %}
        </div>
        {% endif %}
    </header>

    <article class="mt-5">
        {% block article %}

        {% endblock %}
    </article>

    <footer class="mt-5">
        <br>
        <br>
        <p class="text-center md:text-left">Equipo: JAP</p>
        <p class="text-center md:text-left"><a href="https://github.com/JAP-WEB/my_movies">GitHub Repository</a></p>
    </footer>
</body>
</html>

movies/templates/movies/index.html
{% extends "movies/base.html" %}
{% block article %}


{% if movie_list %}
    <div id="movie_list" class="flex flex-wrap justify-center">
    {% for movie in movie_list %}
        <div class="flex-none w-full sm:w-48 m-2 border-4 border-blue-700 border-double rounded-lg p-2">
            <a href="/movies/{{ movie.id }}/">
                <img class="w-full h-auto sm:h-64 rounded-lg" 
                     src="https://media.themoviedb.org/t/p/w300_and_h450_bestv2/{{ movie.poster_path }}" 
                     alt="{{ movie.title }} poster">
            </a>
            <div class="p-2">
                <h1 class="whitespace-nowrap overflow-hidden text-ellipsis font-bold">
                    <a class="mt-2" href="/movies/{{ movie.id }}/">{{ movie.title }}</a>
                </h1>
                <p class="whitespace-nowrap overflow-hidden text-ellipsis italic">
                    {{ movie.release_date|date:"F Y" }}
                </p>
                <p class="text-right">
                    ⭐ {{ movie.average_rating|default:"No reviews yet"|floatformat:1 }}
                </p>
            </div>
        </div>
    {% endfor %}
    </div>
{% else %}
    <p class="text-center">No movies are available.</p>
{% endif %}


{% endblock article %}

movies/templates/movies/login.html
{% extends "movies/base.html" %}

{% block article %}

<div class="flex justify-left">
    <button id="returnButton" class="inline-block px-4 py-2 bg-red-600 text-white rounded-md text-center hover:bg-red-700">Return</button>
</div>

<script>
    document.getElementById('returnButton').addEventListener('click', function() {
        history.back();
    });
</script>

<div class="mt-5 flex justify-center">
    <div class="max-w-xl w-full bg-blue-700 text-white p-6 rounded-lg shadow-md">
        <h1 class="text-center text-2xl font-poppins mb-5">Login</h1>
        <h2 class="text-center text-5xl font-poppins my-5">🔒</h2>

        {% if messages %}
        <div class="messages" id="messageContainer" style="display: none;">
            {% for message in messages %}
            <div class="{{ message.tags }}">{{ message }}</div>
            {% endfor %}
        </div>
        <div id="modal" class="fixed z-10 inset-0 overflow-y-auto hidden">
            <div class="flex items-end justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">
                <div class="fixed inset-0 transition-opacity" aria-hidden="true">
                    <div class="absolute inset-0 bg-gray-500 opacity-75"></div>
                </div>
                <span class="hidden sm:inline-block sm:align-middle sm:h-screen" aria-hidden="true">&#8203;</span>
                <div class="inline-block align-bottom bg-white rounded-lg text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-lg sm:w-full">
                    <div class="bg-white px-4 pt-5 pb-4 sm:p-6 sm:pb-4">
                        <div class="sm:flex sm:items-start">
                            <div class="mx-auto flex-shrink-0 flex items-center justify-center h-12 w-12 rounded-full bg-red-100 sm:mx-0 sm:h-10 sm:w-10">
                                <svg class="h-6 w-6 text-red-600" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/>
                                </svg>
                            </div>
                            <div class="mt-3 text-center sm:mt-0 sm:ml-4 sm:text-left">
                                <h3 class="text-lg leading-6 font-medium text-gray-900" id="modal-title">
                                    Invalid user
                                </h3>
                                <div class="mt-2">
                                    <p class="text-sm text-gray-500">
                                        The username or password you entered is incorrect. Please try again.
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="bg-gray-50 px-4 py-3 sm:px-6 sm:flex sm:flex-row-reverse">
                        <button id="closeButton" type="button" class="w-full inline-flex justify-center rounded-md border border-transparent shadow-sm px-4 py-2 bg-red-600 text-base font-medium text-white hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500 sm:ml-3 sm:w-auto sm:text-sm">
                            Close
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <script>
            document.addEventListener('DOMContentLoaded', function() {
                const messageContainer = document.getElementById('messageContainer');
                if (messageContainer && messageContainer.innerHTML.trim() !== "") {
                    const modal = document.getElementById('modal');
                    modal.classList.remove('hidden');
                    const usernameField = document.getElementById('id_username');
                    const passwordField = document.getElementById('id_password');
                    usernameField.value = '';
                    passwordField.value = '';
                    
                    // Cierra el modal después de 5 segundos (5000 milisegundos)
                    setTimeout(function() {
                        modal.classList.add('hidden');
                    }, 5000);
                }
            });

            // Agrega el evento de clic al botón de cerrar
            document.getElementById('closeButton').addEventListener('click', function() {
                document.getElementById('modal').classList.add('hidden');
            });
            
            // Agrega el evento de clic al botón de ojito
            document.getElementById('toggle-password').addEventListener('click', function() {
                const passwordField = document.getElementById('id_password');
                const type = passwordField.getAttribute('type') === 'password' ? 'text' : 'password';
                passwordField.setAttribute('type', type);
            });
            
        </script>
        {% endif %}

        <form method="post" class="mb-8">
            {% csrf_token %}
            <div class="mb-4">
                <label for="id_username" class="block text-white text-sm font-bold mb-2">Username</label>
                <div class="relative text-black">
                    {{ form.username }}
                </div>
            </div>
            
            <div class="mb-4">
                <label for="id_password" class="block text-white text-sm font-bold mb-2">Password</label>
                <div class="relative text-black">
                    {{ form.password }}
                    <button type="button" class="absolute inset-y-0 right-0 px-3 py-2 text-white" id="toggle-password">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-gray-500 hover:text-gray-700 cursor-pointer" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0zM9 12s1.5 2 3 2 3-2 3-2m-9 3.5a9.31 9.31 0 0012 0m-12 0a9.31 9.31 0 0012 0m-12-9a9.31 9.31 0 0012 0m-12 0a9.31 9.31 0 0012 0" />
                            <path d="M0 0h24v24H0z" fill="none"/>
                        </svg>
                    </button>
                </div>
            </div>


            <div class="text-center"> <!-- Contenedor para centrar el botón -->
                <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-5 focus:outline-none focus:shadow-outline">
                    Sign In
                </button>
            </div>
        </form>

        <div class="text-center mt-4">
            <a class="inline-block align-baseline font-bold text-sm text-blue-500 hover:text-blue-800" href="{% url 'register' %}">
                Create an Account
            </a>
        </div>
    </div>
</div>

<script>
     const togglePassword = document.getElementById('toggle-password');
    const passwordField = document.getElementById('password-field');

    togglePassword.addEventListener('click', function() {
        const type = passwordField.getAttribute('type') === 'password' ? 'text' : 'password';
        passwordField.setAttribute('type', type);
    });
</script>


            
{% endblock %}

movies/templates/movies/movie_detail.html
{% extends "movies/base.html" %}

{% block article %}
<div class="flex justify-between mb-4">
    <a href="{% url 'index' %}" class="inline-block px-4 py-2 bg-red-600 text-white rounded-md text-center hover:bg-red-700">Return</a>
    <a href="review" class="inline-block px-4 py-2 bg-blue-600 text-white rounded-md text-center hover:bg-blue-700">Write your review</a>
</div>

<div class="flex flex-col md:flex-row bg-blue-700 my-4 justify-center items-center">
    <div class="w-full md:w-1/3 mx-2 my-2 overflow-hidden"> <!-- Asegúrate de que el contenedor tenga un ancho del 100% y ningún margen adicional -->
        <img class="mx-auto w-full h-auto border-4 border-black p-1" src="https://media.themoviedb.org/t/p/w300_and_h450_bestv2/{{movie.poster_path}}">
    </div>
    <header class="w-full md:w-2/3 px-4 my-4">
        <h1 class="movie-title text-2xl md:text-4xl font-bold text-center"><strong>{{movie.title}}</strong></h1>
        <div class="movie-info text-center">
            <p>- {{ movie.release_date|date:"Y" }} -</p>
            <ul class="movie-genre">
                {% for genre in movie.genres.all %}
                    <li class="inline">{{ genre.name }}{% if not forloop.last %} | {% endif %}</li>
                {% endfor %}
            </ul>
            <p>⏰ {{movie.running_time}} minutes</p>
        </div>   
        <h1>🎥 Overview</h1>
        <p class="text-justify">
            {{ movie.overview }} 
        </p>
        <h2>Average Rating: ⭐ <strong>{{ average_rating|default:"No reviews yet"|floatformat:2 }}</strong></h2>
        <details>
            <summary class="font-bold">Production Details</summary>
            <p> 💸 Budget: ${{ movie.budget }} </p>
            <p> 💰 Revenue: ${{ movie.revenue }} </p>
        </details>
        <details>
            <summary class="font-bold">Actors</summary>
            {% if actors %}
                <ul>
                {% for actor in actors %}
                    <li>
                        <p>{{ actor.person }} ({{ actor.job }})</p>
                    </li>
                {% endfor %}
                </ul>
            {% else %}
                <p>No actors are available.</p>
            {% endif %}
        </details>
    </header>
</div>


<div>
    <h1 class="text-2xl font-bold my-2 text-center">💭 Reviews</h1>
    {% if review_list %}
        <div id="review_list" class="flex flex-wrap justify-center gap-4">
        {% for review in review_list %}
            <div class="flex flex-col bg-blue-700 my-4 p-4 w-full sm:w-[calc(33.333%-1rem)] rounded-lg">
                <p class="text-justify"><strong>{{ review.user }} </strong><br><strong> ⭐ {{ review.rating }} </strong> <br>Reseña: {{ review.review }}</p>
            </div>
        {% endfor %}
        </div>
    {% else %}
        <p>No reviews are available.</p>
    {% endif %}
</div>

<div>
    <h1 class="text-2xl font-bold my-4 text-center">🎬 Recommendations</h1>
    {% if recommendations %}
        <div id="movie_list" class="flex flex-wrap justify-center items-center">
        {% for movie in recommendations %}
            <div class="flex-none w-full sm:w-48 sm:h-87 m-2 my-4 mx-auto border-4 border-blue-700 border-double rounded-lg p-2">
                <a href="/movies/{{ movie.id }}/">
                    <img class="mx-auto w-auto h-auto rounded-lg" src="https://media.themoviedb.org/t/p/w300_and_h450_bestv2/{{movie.poster_path}}" alt="{{movie.title}} poster">
                </a>
                <div class="text-center">
                    <h1 class="text-nowrap text-ellipsis overflow-hidden font-bold mt-2">
                        <a class="text-blue-700" href="/movies/{{ movie.id }}/">{{ movie.title }}</a>
                    </h1>
                    <p class="text-blue-700">⭐ {{ movie.average_rating|default:"No reviews yet"|floatformat:1 }}</p>
                </div>
            </div>
        {% endfor %}
        </div>
    {% else %}
        <p>No recommendations are available.</p>
    {% endif %}
</div>

{% endblock %}

movies/templates/movies/name.html
{% extends "movies/base.html" %}

{% block article %}

<div class="flex flex-col w-2/3 ml-16 mt-8 mb-8">
    <form hx-post="/movies/your_name/" hx-swap="outerHTML" _="on htmx:afterOnLoad log 'Saved' wait 2s set #submit-button.innerText to 'Save'">
        {% csrf_token %}
        {{ form }}
        
        <div class="mt-6 flex items-center justify-end gap-x-6">
            <button type="button" class="text-sm font-semibold leading-6 text-gray-900">Cancel</button>
            <button id="submit-button" type="submit" class="rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm 
                                        hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 
                                        focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
            >Save</button>
        </div> 
    </form>
</div>

{% endblock %}

movies/templates/movies/name_ok.html
    <form hx-post="/movies/your_name/" hx-swap="outerHTML" _="on htmx:afterOnLoad log 'Saved' wait 3s set #submit-button.innerText to 'Save'">
        {% csrf_token %}
        {{ form }}
            
        <div class="mt-6 flex items-center justify-end gap-x-6">
            <button type="button" class="text-sm font-semibold leading-6 text-gray-900">Cancel</button>
            <button id="submit-button" type="submit" class="rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm 
                                        hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 
                                        focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
            >Se guardó el nombre: {{form.cleaned_data.your_name}}</button>
        </div> 
    </form>

movies/templates/movies/review.html
{% extends "movies/base.html" %}

{% block article %}
<style>
    .fixed-size {
        width: 100px; /* Tamaño fijo para el select de calificación */
    }
    .label-white {
        color: white; /* Color blanco para las etiquetas */
    }
</style>
<div class="mt-6 container mx-auto px-4">
    <form method="post" class="w-full">
        {% csrf_token %}
        <div class="text-center font-bold text-3xl my-4">
            <h2 class="text-xl sm:text-2xl md:text-3xl">{{ movie_name }}</h2>
        </div>
        <div class="mb-4">
            <label for="id_rating" class="block text-sm font-medium label-white">{{ form.rating.label }}</label>
            <div class="my-2 text-black">
                {{ form.rating }}
            </div>
        </div>
        <div class="my-8">
            <label for="id_review" class="block text-sm font-medium label-white">{{ form.review.label }}</label>
            <div class="my-2 text-black">
                {{ form.review }}
            </div>
        </div>
        <div class="mt-6 flex flex-col sm:flex-row items-center justify-between">
            <a href="{% url 'movie_detail' movie_id=movie_id %}" class="w-full sm:w-auto mb-2 sm:mb-0 sm:mr-2 px-4 py-2 bg-red-600 text-white rounded-md text-center hover:bg-red-700">Return</a>
            <button type="submit" class="w-full sm:w-auto px-4 py-2 bg-blue-600 text-white rounded-md text-center hover:bg-blue-700">Send</button>
        </div>
    </form>
</div>
{% endblock %}